### ISSUE TITLE
archive project

### ISSUE THREAD

**Issue by slachiewicz** [codehaus-plexus/plexus-interactivity#29]

**Comment by michael-o** [comment]
Are you certain about this? I have done a release this year because of a bug.

**Comment by slachiewicz** [comment]
I've checked here:

https://github.com/search?q=org%3Aapache+plexus-interactivity&type=code
https://github.com/search?q=org%3Acodehaus-plexus+plexus-interactivity&type=repositories
https://github.com/search?q=org%3Amojohaus+plexus-interactivity

and only impl is here with jline from 2008

**Comment by michael-o** [comment]
> I've checked here:
> 
> https://github.com/search?q=org%3Aapache+plexus-interactivity&type=code https://github.com/search?q=org%3Acodehaus-plexus+plexus-interactivity&type=repositories https://github.com/search?q=org%3Amojohaus+plexus-interactivity
> 
> and only impl is here with jline from 2008

I consider this incomplete, fixed this somewhere for Maven recently. @gnodet helped me to understand the issue.

**Comment by slachiewicz** [comment]
you are right - maven-wagon, maven-release-plugin, achetype 

https://github.com/search?q=org%3Aapache+plexus-interactivity-api&type=code

**Comment by gnodet** [comment]
> > I've checked here:
> > https://github.com/search?q=org%3Aapache+plexus-interactivity&type=code https://github.com/search?q=org%3Acodehaus-plexus+plexus-interactivity&type=repositories https://github.com/search?q=org%3Amojohaus+plexus-interactivity
> > and only impl is here with jline from 2008
> 
> I consider this incomplete, fixed this somewhere for Maven recently. @gnodet helped me to understand the issue.

Not sure what you want, but `mvnd` definitely needs it. I'm not sure there are other implementations, but the eclipse integration may have one too.  Basically, if you want to integrate maven in an environment which is not a pure command line as usual, you need this api.  And plugin that do ask users for something should use this api.
