### ISSUE TITLE
Please speficy versions of dependencies in the parent pom

### ISSUE THREAD

**Issue by pgrt** [codehaus-plexus/plexus-interactivity#34]
Hello,

In Debian plexus-interactivity is packaged, and we are facing a bug with version 1.1 as the two child poms depend on org.codehaus.plexus:artifactId>plexus-utils and org.codehaus.plexus:plexus-container-default although no version number is provided. Then the pom files that are shipped in the build package have no versioning information and it raises errors about "dependencies.dependency.version" being missing for plexus-interactivity as soon as one uses maven-javadoc-plugin, which depends on plexus-interactivity.

Setting version information in the parent POM, e.g. with

<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>3.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-container-default</artifactId>
      <version>2.1.1</version>
    </dependency>
  </dependencies>
</dependencyManagement>

solve the issue.

Best regards,

Pierre

**Comment by michael-o** [comment]
Please share the full message.

**Comment by pgrt** [comment]
Sure!

I was building the latest upstream version of Byte Buddy and got the following message:

[INFO] --- maven-javadoc-plugin:3.0.1:jar (default-cli) @ byte-buddy-parent ---
[WARNING] The POM for org.codehaus.plexus:plexus-interactivity-api:jar:debian is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model fo
r org.codehaus.plexus:plexus-interactivity-api:debian
[ERROR] 'dependencies.dependency.version' for org.codehaus.plexus:plexus-utils:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.codehaus.plexus:plexus-container-default:jar is missing. @

The attached patch allowed me to remove this issue.
[dependency_management.txt](https://github.com/codehaus-plexus/plexus-interactivity/files/9742358/dependency_management.txt)

Best,
Pierre

**Comment by michael-o** [comment]
@pgrt, please open a PR, I will review and merge it.

**Comment by pgrt** [comment]
Hi @michael-o ,

Sure! You will get it soon.

Best,
Pierre

**Comment by michael-o** [comment]
I cannot confirm this. The parent contains the identical dep mgmt section: https://search.maven.org/artifact/org.codehaus.plexus/plexus-components/10.0/pom

Can ypu double check?

**Comment by michael-o** [comment]
8a9b43598b765928c481260d687b38ca9012d3ce fixed this issue as far as I can see.

**Comment by pgrt** [comment]
Hello,

Thanks for investigating further. Now I understand: the version information is correctly provided in the plexus-components pom... yet we haven't packaged it into Debian as it is in another repository and basically ``one source package = one upstream repository''... Which is the reason why this version information is not found during Debian builds.

So the issue is definitely Debian-specific. Sorry for the noise about it, and thanks for helping me to figure it out.

I am closing the issue, you can also close the PR of course.

Cheers,
Pierre
